export const OCCUPATIONS = [
  'accounting-audit',
  'agrifood-agritech',
  'architecture-urban-planning',
  'arts-design',
  'clerical-office-administration',
  'construction-building-trades',
  'consulting-advisory',
  'customer-service',
  'data-management-analytics',
  'education-teaching',
  'engineering',
  'entertainment-performing-arts',
  'environment-natural-resources',
  'fashion-design-modeling',
  'financial-services',
  'healthcare',
  'hospitality',
  'human-resources-recruiting',
  'information-technology',
  'insurance',
  'law-enforcement-security',
  'legal',
  'management-administration',
  'manufacturing',
  'marketing',
  'operations-supply-chain',
  'public-relations-communications',
  'real-estate',
  'research-development',
  'retail',
  'sales',
  'science',
  'social-services',
  'student',
  'sports-recreation',
  'sustainability',
  'tax',
  'transportation-logistics',
  'writing-editing-journalism',
  'others',
] as const;

export type Occupation = (typeof OCCUPATIONS)[number];
