export const AREAS_OF_STUDY = [
  {value: '', label: 'Choose your area of studies'},
  {value: 'agriculture', label: 'Agriculture'},
  {value: 'anthropology', label: 'Anthropology'},
  {value: 'applied-mathematics', label: 'Applied mathematics'},
  {value: 'archaeology', label: 'Archaeology'},
  {value: 'architecture-and-design', label: 'Architecture and design'},
  {value: 'area-studies', label: 'Area studies'},
  {value: 'astronomy', label: 'Astronomy'},
  {value: 'biology', label: 'Biology'},
  {value: 'business', label: 'Business'},
  {value: 'chemical-engineering', label: 'Chemical engineering'},
  {value: 'chemistry', label: 'Chemistry'},
  {value: 'civil-engineering', label: 'Civil engineering'},
  {value: 'computer-science', label: 'Computer science'},
  {value: 'divinity', label: 'Divinity'},
  {value: 'earth-science', label: 'Earth science'},
  {value: 'economics', label: 'Economics'},
  {value: 'education', label: 'Education'},
  {value: 'educational-technology', label: 'Educational technology'},
  {value: 'engineering-and-technology', label: 'Engineering and technology'},
  {value: 'environmental-studies-and-forestry', label: 'Environmental studies and forestry'},
  {value: 'ethnic-and-cultural-studies', label: 'Ethnic and cultural studies'},
  {value: 'family-and-consumer-science', label: 'Family and consumer science'},
  {value: 'futurology', label: 'Futurology'},
  {value: 'geography', label: 'Geography'},
  {
    value: 'human-physical-performance-and-recreation',
    label: 'Human physical performance and recreation',
  },
  {value: 'interdisciplinary-studies', label: 'Interdisciplinary studies'},
  {
    value: 'journalism-media-studies-and-communication',
    label: 'Journalism, media studies and communication',
  },
  {value: 'law', label: 'Law'},
  {value: 'library-and-museum-studies', label: 'Library and museum studies'},
  {value: 'life-science', label: 'Life science'},
  {value: 'linguistics', label: 'Linguistics'},
  {value: 'logic', label: 'Logic'},
  {value: 'materials-science', label: 'Materials science'},
  {value: 'mathematics', label: 'Mathematics'},
  {value: 'mechanical-engineering', label: 'Mechanical engineering'},
  {value: 'medicine-and-health', label: 'Medicine and health'},
  {value: 'military-sciences', label: 'Military sciences'},
  {value: 'performing-arts', label: 'Performing arts'},
  {value: 'philosophy', label: 'Philosophy'},
  {value: 'physical-science', label: 'Physical Science'},
  {value: 'physics', label: 'Physics'},
  {value: 'political-science', label: 'Political science'},
  {value: 'psychology', label: 'Psychology'},
  {value: 'public-administration', label: 'Public administration'},
  {value: 'public-policy', label: 'Public policy'},
  {value: 'pure-mathematics', label: 'Pure mathematics'},
  {value: 'religion', label: 'Religion'},
  {value: 'religious-studies', label: 'Religious studies'},
  {value: 'social-work', label: 'Social work'},
  {value: 'sociology', label: 'Sociology'},
  {value: 'space-sciences', label: 'Space sciences'},
  {value: 'statistics', label: 'Statistics'},
  {value: 'systems-science', label: 'Systems science'},
  {value: 'theology', label: 'Theology'},
  {value: 'transportation', label: 'Transportation'},
  {value: 'visual-arts', label: 'Visual arts'},
  {value: 'others', label: 'Others'},
];
