export const OCCUPATIONS = [
  {value: '', label: 'Choose your occupation'},
  {value: 'accounting-audit', label: 'Accounting / Audit'},
  {value: 'agrifood-agritech', label: 'Agri-food / Agri-tech'},
  {value: 'architecture-urban-planning', label: 'Architecture & Urban Planning'},
  {value: 'arts-design', label: 'Arts / Design'},
  {value: 'clerical-office-administration', label: 'Clerical / Office Administration'},
  {value: 'construction-building-trades', label: 'Construction & Building Trades'},
  {value: 'consulting-advisory', label: 'Consulting / Advisory'},
  {value: 'customer-service', label: 'Customer Service'},
  {value: 'data-management-analytics', label: 'Data Management / Analytics'},
  {value: 'education-teaching', label: 'Education / Teaching'},
  {value: 'engineering', label: 'Engineering'},
  {value: 'entertainment-performing-arts', label: 'Entertainment / Performing Arts'},
  {value: 'environment-natural-resources', label: 'Environment / Natural Resources'},
  {value: 'fashion-design-modeling', label: 'Fashion Design / Modeling'},
  {value: 'financial-services', label: 'Financial Services'},
  {value: 'healthcare', label: 'Healthcare'},
  {value: 'hospitality', label: 'Hospitality'},
  {value: 'human-resources-recruiting', label: 'Human Resources / Recruiting'},
  {value: 'information-technology', label: 'Information Technology'},
  {value: 'insurance', label: 'Insurance'},
  {value: 'law-enforcement-security', label: 'Law Enforcement & Security'},
  {value: 'legal', label: 'Legal'},
  {value: 'management-administration', label: 'Management & Administration'},
  {value: 'manufacturing', label: 'Manufacturing'},
  {value: 'marketing', label: 'Marketing'},
  {value: 'operations-supply-chain', label: 'Operations / Supply Chain'},
  {value: 'public-relations-communications', label: 'Public Relations / Communications'},
  {value: 'real-estate', label: 'Real Estate'},
  {value: 'research-development', label: 'Research & Development'},
  {value: 'retail', label: 'Retail'},
  {value: 'sales', label: 'Sales'},
  {value: 'science', label: 'Science'},
  {value: 'social-services', label: 'Social Services'},
  {value: 'sports-recreation', label: 'Sports & Recreation'},
  {value: 'sustainability', label: 'Sustainability'},
  {value: 'tax', label: 'Tax'},
  {value: 'transportation-logistics', label: 'Transportation & Logistics'},
  {value: 'writing-editing-journalism', label: 'Writing & Editin / Journalism'},
  {value: 'others', label: 'Others'},
];
