name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install root dependencies
        run: npm install

      - name: Install workspace dependencies
        run: npm install --workspaces
        working-directory: ./cs3219-ay2526s1-project-g03

      - name: Run tests
        run: npx jest --coverage
        working-directory: ./cs3219-ay2526s1-project-g03

      - name: Upload results to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./cs3219-ay2526s1-project-g03/coverage/